### ISSUE TITLE
documentation is misleading

### ISSUE THREAD

**Issue by venil7** [twolfson/canvas-to-pixels#2]
Theres something wrong with documentation

```
var canvasToPixels = require('canvas-to-pixels');
canvasToPixels({
  width: 10,
  height: 10,
  js: (canvas, cb) { // <----- I think an arrow is missing here
    var context = canvas.getContext('2d');
    context.fillStyle = '#BADA55';
    context.fillRect(0, 0, 10, 10);
    cb();
  }
}, function receivePixels (err, pixels) {
  // pixels is [186,218,85,255,186,218, ..., 255]
});
```

and it should read: 
``` js: (canvas, cb) => { ```

documentation says: `js Object - Container for commands to run against a canvas instance`

this is not valid Javascript

**Comment by twolfson** [comment]
Ah, sorry about that. This was written 3 years ago so I think I was trying out a different documentation style (i.e. skipping `function` for conciseness) instead of using an arrow function. The `js Object` documentation is likely caused by me rushing to release all the separate parts of `gifsockets-server`

I've corrected/updated the documentation. Thanks for the issue
